# .NET Desktop


# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  name: 'Default'



steps:
- task: NuGetToolInstaller@1


- task: UiPathPack@5
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\UiPath\ProcessNetworkEnquiries\project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@5
  inputs:
    orchestratorConnection: 'AzureDevOps-UiPath'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Autopilot'
    processName: 'ProcessNetworkEnquiries'



