# .NET Desktop

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UiPathDeploy@5
  inputs:
    orchestratorConnection: 'AzureDevOps-UiPath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/ProcessNetworkEnquiry.1.0.$(Build.BuildId).nupkg'
    folderName: 'DefaultTenant'
    processName: 'ProcessNetworkEnquiry'


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
